# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run YARA-Forge

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
  
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ python3-dev libre2-dev
  
    - name: Confirm libre2-dev headers
      run: |
        dpkg -L libre2-dev | grep re2.h || echo "re2.h not found"
        test -f /usr/include/re2/re2.h && echo "Header exists ✅" || (echo "Header missing ❌" && exit 1)

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r qa/yaraQA/requirements.txt

    - name: Run YARA-Forge
      run: |
        python yara-forge.py
